# Generated by Django 5.2.13 on 2026-05-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_employee_name_employee_first_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-clock_in']},
        ),
    ]
